# Dockerfile.llm
FROM nvidia/cuda:11.8.0-runtime-ubuntu20.04

ENV DEBIAN_FRONTEND=noninteractive
ENV APT_KEY_DONT_WARN_ON_DANGEROUS_USAGE=1

RUN apt-get update && apt-get install -y \
    python3 python3-pip git curl lsof iptables \
    && apt-get clean \
    && ln -s /usr/bin/python3 /usr/bin/python \
    && pip install --upgrade pip \
    && rm -rf /var/lib/apt/lists/*

WORKDIR /app
COPY . .
RUN pip install -r requirements.txt

# ✅ 아무것도 실행하지 않음. vLLM은 API가 컨트롤
CMD ["tail", "-f", "/dev/null"]

