version: "2.4"

services:
  api:
    build:
      context: .                
      dockerfile: Dockerfile   
    container_name: malpyeong_api
    volumes:
      - ./scripts:/app/scripts
      - ./schedule:/app/schedule
      - ./state:/app/state
    environment:
      - SCRIPT_DIR=/app/scripts
      - SCHEDULE_CSV=/app/schedule/schedule(day).csv
    ports:
      - "5020:5020"
    command: python api_main.py

  llm0:
    build: ./llm
    container_name: llm0
    devices:
      - /dev/nvidia0:/dev/nvidia0
    environment:
      - CONTAINER_NAME=llm0
      - SCHEDULE_CSV=/app/schedule/schedule(day).csv
      - SCRIPT_DIR=/app/scripts
    volumes:
      - ./schedule:/app/schedule
      - ./scripts:/app/scripts
      - ./state:/app/state
      - /mnt/llm_cache:/mnt/llm_cache
    ports:
      - "5021:5021"
    command: python serve_main.py

  llm1:
    build: ./llm
    container_name: llm1
    devices:
      - /dev/nvidia1:/dev/nvidia1
    environment:
      - CONTAINER_NAME=llm1
      - SCHEDULE_CSV=/app/schedule/schedule(day).csv
      - SCRIPT_DIR=/app/scripts
    volumes:
      - ./schedule:/app/schedule
      - ./scripts:/app/scripts
      - ./state:/app/state
      - /mnt/llm_cache:/mnt/llm_cache
    ports:
      - "5022:5022"
    command: python serve_main.py

  llm2:
    build: ./llm
    container_name: llm2
    devices:
      - /dev/nvidia2:/dev/nvidia2
    environment:
      - CONTAINER_NAME=llm2
      - SCHEDULE_CSV=/app/schedule/schedule(day).csv
      - SCRIPT_DIR=/app/scripts
    volumes:
      - ./schedule:/app/schedule
      - ./scripts:/app/scripts
      - ./state:/app/state
      - /mnt/llm_cache:/mnt/llm_cache
    ports:
      - "5023:5023"
    command: python serve_main.py

  llm3:
    build: ./llm
    container_name: llm3
    devices:
      - /dev/nvidia3:/dev/nvidia3
    environment:
      - CONTAINER_NAME=llm3
      - SCHEDULE_CSV=/app/schedule/schedule(day).csv
      - SCRIPT_DIR=/app/scripts
    volumes:
      - ./schedule:/app/schedule
      - ./scripts:/app/scripts
      - ./state:/app/state
      - /mnt/llm_cache:/mnt/llm_cache
    ports:
      - "5024:5024"
    command: python serve_main.py
