# Dockerfile.api
FROM python:3.8-slim

ENV DEBIAN_FRONTEND=noninteractive

RUN apt-get update && apt-get install -y \
    git curl iptables lsof \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*\

WORKDIR /app

COPY . .

RUN pip install --upgrade pip
RUN pip install -r requirements.txt

CMD ["python", "api_main.py"]
