version: "2.4"


networks:
  malpyeong_net:
    driver: bridge
    ipam:
      config:
        - subnet: 172.18.123.0/24

services:
  # ───────────────────────────────
  # 1) API + 스케줄러 (호스트 5020)
  # ───────────────────────────────
  api:
    build:
      context: .            # 프로젝트 루트의 Dockerfile 사용
      dockerfile: Dockerfile
    container_name: malpyeong_api
    volumes:
      - ./scripts:/app/scripts
      - ./schedule:/app/schedule
      - ./state:/app/state
      - /data:/data
    environment:
      - SCRIPT_DIR=/app/scripts
      - SCHEDULE_CSV=/app/schedule/schedule(day).csv
    ports:
      - "5020:5020"
    cap_add:
      - NET_ADMIN
    networks:
      - malpyeong_net
    command: python api_main.py

  # ───────────────────────────────
  # 2) vLLM 추론 컨테이너 4대 (5021~5024)
  # ───────────────────────────────
  llm0:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: llm4
    devices:
      - /dev/nvidia4:/dev/nvidia4
    environment:
      - CONTAINER_NAME=llm4
      - SCHEDULE_CSV=/app/schedule/schedule(day).csv
      - SCRIPT_DIR=/app/scripts
    volumes:
      - ./schedule:/app/schedule
      - ./scripts:/app/scripts
      - ./state:/app/state
      - /mnt/llm_cache:/mnt/llm_cache
      - /data:/data
    ports:
      - "5021:5021"
    networks:
      - malpyeong_net
    command: python llm/serve_main.py

  llm1:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: llm5
    devices:
      - /dev/nvidia5:/dev/nvidia5
    environment:
      - CONTAINER_NAME=llm5
      - SCHEDULE_CSV=/app/schedule/schedule(day).csv
      - SCRIPT_DIR=/app/scripts
    volumes:
      - ./schedule:/app/schedule
      - ./scripts:/app/scripts
      - ./state:/app/state
      - /mnt/llm_cache:/mnt/llm_cache
      - /data:/data
    ports:
      - "5022:5022"
    networks:
      - malpyeong_net
    command: python llm/serve_main.py

  llm2:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: llm6
    devices:
      - /dev/nvidia6:/dev/nvidia6
    environment:
      - CONTAINER_NAME=llm6
      - SCHEDULE_CSV=/app/schedule/schedule(day).csv
      - SCRIPT_DIR=/app/scripts
    volumes:
      - ./schedule:/app/schedule
      - ./scripts:/app/scripts
      - ./state:/app/state
      - /mnt/llm_cache:/mnt/llm_cache
      - /data:/data
    ports:
      - "5023:5023"
    networks:
      - malpyeong_net
    command: python llm/serve_main.py

  llm3:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: llm7
    devices:
      - /dev/nvidia7:/dev/nvidia7
    environment:
      - CONTAINER_NAME=llm7
      - SCHEDULE_CSV=/app/schedule/schedule(day).csv
      - SCRIPT_DIR=/app/scripts
    volumes:
      - ./schedule:/app/schedule
      - ./scripts:/app/scripts
      - ./state:/app/state
      - /mnt/llm_cache:/mnt/llm_cache
      - /data:/data
    ports:
      - "5024:5024"
    networks:
      - malpyeong_net
    command: python llm/serve_main.py
