

services:
  llm0:
    build:
      context: ./llm           # Dockerfile 위치
      dockerfile: Dockerfile
    container_name: llm0
    environment:
      - CONTAINER_NAME=llm0
      - SCHEDULE_CSV=/app/schedule/schedule(day).csv
      - SCRIPT_DIR=/app/scripts
    device_requests:
      - driver: nvidia
        count: 1
        device_ids: ["0"]
        capabilities: ["gpu"]
    volumes:
      - ./schedule:/app/schedule    # 스케줄러 코드·CSV
      - ./scripts:/app/scripts      # 스위치 스크립트 등
      - ./state:/app/state          # 상태 기록
      - /mnt/llm_cache:/mnt/llm_cache
    ports:
      - "5021:5021"

  llm1:
    build:
      context: ./llm
      dockerfile: Dockerfile
    container_name: llm1
    environment:
      - CONTAINER_NAME=llm1
      - SCHEDULE_CSV=/app/schedule/schedule(day).csv
      - SCRIPT_DIR=/app/scripts
    device_requests:
      - driver: nvidia
        count: 1
        device_ids: ["1"]
        capabilities: ["gpu"]
    volumes:
      - ./schedule:/app/schedule
      - ./scripts:/app/scripts
      - ./state:/app/state
      - /mnt/llm_cache:/mnt/llm_cache
    ports:
      - "5022:5022"

  llm2:
    build:
      context: ./llm
      dockerfile: Dockerfile
    container_name: llm2
    environment:
      - CONTAINER_NAME=llm2
      - SCHEDULE_CSV=/app/schedule/schedule(day).csv
      - SCRIPT_DIR=/app/scripts
    device_requests:
      - driver: nvidia
        count: 1
        device_ids: ["2"]
        capabilities: ["gpu"]
    volumes:
      - ./schedule:/app/schedule
      - ./scripts:/app/scripts
      - ./state:/app/state
      - /mnt/llm_cache:/mnt/llm_cache
    ports:
      - "5023:5023"

  llm3:
    build:
      context: ./llm
      dockerfile: Dockerfile
    container_name: llm3
    environment:
      - CONTAINER_NAME=llm3
      - SCHEDULE_CSV=/app/schedule/schedule(day).csv
      - SCRIPT_DIR=/app/scripts
    device_requests:
      - driver: nvidia
        count: 1
        device_ids: ["3"]
        capabilities: ["gpu"]
    volumes:
      - ./schedule:/app/schedule
      - ./scripts:/app/scripts
      - ./state:/app/state
      - /mnt/llm_cache:/mnt/llm_cache
    ports:
      - "5024:5024"
